"""
From powershell:
$PSDefaultParameterValues['Out-File:Encoding'] = 'utf8'
python .\klc.py > main.c

From linux subsystem for windows:
gcc -std=c89 -Werror -Wpedantic -Wall -Wno-unused-function -Wno-unused-variable main.c && \
cp main.{c,cc} && \
g++ -std=c++98 -Werror -Wpedantic -Wall -Wno-unused-function -Wno-unused-variable main.cc && \
./a.out
"""
from typing import NamedTuple, Tuple, List, Union, Optional, Callable, Iterable
import abc
import re
import typing
import contextlib
import sys


SYMBOLS = [
    ';',
    '.', ',', '!', '@', '^', '&', '+', '-', '/', '%', '*', '.', '=', '==', '<',
    '>', '<=', '>=', '(', ')', '{', '}', '[', ']',
]

KEYWORDS = {'class', 'trait', 'if', 'else', 'while', 'break', 'continue'}

PRIMITIVE_TYPES = {
    'void',
    'int',
    'long',
    'size_t',
    'double',
    'function',
}


PRELUDE = r"""/* Autogenerated by the KL Compiler */
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#define KLC_TAG_INT 0
#define KLC_TAG_LONG 1
#define KLC_TAG_SIZE_T 2
#define KLC_TAG_DOUBLE 3
#define KLC_TAG_FUNCTION 4
#define KLC_TAG_OBJECT 5

typedef struct KLC_header KLC_header;
typedef struct KLC_typeinfo KLC_typeinfo;
typedef struct KLC_var KLC_var;
typedef KLC_var (*KLC_Function)(int, KLC_var*);

struct KLC_header {
  KLC_typeinfo* type;
  size_t refcnt;
  KLC_header* next;
};

struct KLC_typeinfo {
  const char* name;
  void (*deleter)(KLC_header*, KLC_header**);
};

struct KLC_var {
  int tag;
  union {
    int i;
    long l;
    size_t s;
    double d;
    KLC_Function f;
    KLC_header* obj;
  } u;
};

void KLC_retain(KLC_header *obj) {
  if (obj) {
    obj->refcnt++;
  }
}

void KLC_retain_var(KLC_var v) {
  if (v.tag == KLC_TAG_OBJECT) {
    KLC_retain(v.u.obj);
  }
}

void KLC_partial_release(KLC_header* obj, KLC_header** delete_queue) {
  if (obj) {
    if (obj->refcnt) {
      obj->refcnt--;
    } else {
      obj->next = *delete_queue;
      *delete_queue = obj;
    }
  }
}

void KLC_partial_release_var(KLC_var v, KLC_header** delete_queue) {
  if (v.tag == KLC_TAG_OBJECT) {
    KLC_partial_release(v.u.obj, delete_queue);
  }
}

void KLC_release(KLC_header *obj) {
  KLC_header* delete_queue = NULL;
  KLC_partial_release(obj, &delete_queue);
  while (delete_queue) {
    obj = delete_queue;
    delete_queue = delete_queue->next;
    obj->type->deleter(obj, &delete_queue);
    free(obj);
  }
}

void KLC_release_var(KLC_var v) {
  if (v.tag == KLC_TAG_OBJECT) {
    KLC_release(v.u.obj);
  }
}

KLC_var KLC_int_to_var(int i) {
  KLC_var ret;
  ret.tag = KLC_TAG_INT;
  ret.u.i = i;
  return ret;
}

KLC_var KLC_long_to_var(long l) {
  KLC_var ret;
  ret.tag = KLC_TAG_LONG;
  ret.u.l = l;
  return ret;
}

KLC_var KLC_size_t_to_var(size_t s) {
  KLC_var ret;
  ret.tag = KLC_TAG_SIZE_T;
  ret.u.s = s;
  return ret;
}

KLC_var KLC_double_to_var(double d) {
  KLC_var ret;
  ret.tag = KLC_TAG_DOUBLE;
  ret.u.d = d;
  return ret;
}

KLC_var KLC_function_to_var(KLC_Function f) {
  KLC_var ret;
  ret.tag = KLC_TAG_FUNCTION;
  ret.u.f = f;
  return ret;
}

KLC_var KLC_object_to_var(KLC_header* obj) {
  KLC_var ret;
  ret.tag = KLC_TAG_OBJECT;
  ret.u.obj = obj;
  return ret;
}

typedef struct KLCNString KLCNString;
struct KLCNString {
  KLC_header header;
  size_t size;
  char *buffer;
};

void KLC_deleteString(KLC_header* robj, KLC_header** dq) {
  KLCNString *obj = (KLCNString*) robj;
  free(obj->buffer);
}

KLC_typeinfo KLC_typeString = {
  "String",
  KLC_deleteString
};

KLCNString* KLC_mkstr(const char *str) {
  KLCNString* obj = (KLCNString*) malloc(sizeof(KLCNString));
  size_t len = strlen(str);
  char* buffer = (char*) malloc(sizeof(char) * (len + 1));
  strcpy(buffer, str);
  obj->header.type = &KLC_typeString;
  obj->header.refcnt = 0;
  obj->header.next = NULL;
  obj->size = len;
  obj->buffer = buffer;
  return obj;
}

void KLCNputs(KLCNString *s) {
  printf("%s\n", s->buffer);
}

void KLCNmain();

KLC_var KLC_zero;

int main() {
  KLCNmain();
  return 0;
}

"""


class Source(NamedTuple):
    filename: str
    data: str


class Token:
    __slots__ = ['type', 'value', 'source', 'i']

    def __init__(self,
                 type: str,
                 value: object = None,
                 source: Optional[Source] = None,
                 i: Optional[int] = None) -> None:
        self.type = type
        self.value = value
        self.source = source
        self.i = i

    def _key(self) -> Tuple[str, object]:
        return self.type, self.value

    def __eq__(self, other: object) -> bool:
        return isinstance(other, Token) and self._key() == other._key()

    def __hash__(self) -> int:
        return hash(self._key())

    def __repr__(self) -> str:
        return f'Token({repr(self.type)}, {repr(self.value)})'

    @property
    def lineno(self) -> int:
        assert self.source is not None
        assert self.i is not None
        return self.source.data.count('\n', 0, self.i) + 1

    @property
    def colno(self) -> int:
        assert self.source is not None
        assert self.i is not None
        return self.i - self.source.data.rfind('\n', 0, self.i)

    @property
    def line(self) -> str:
        assert self.source is not None
        assert self.i is not None
        s = self.source.data
        a = s.rfind('\n', 0, self.i) + 1
        b = s.find('\n', self.i)
        if b == -1:
            b = len(s)
        return s[a:b]

    @property
    def info(self) -> str:
        line = self.line
        colno = self.colno
        lineno = self.lineno
        spaces = ' ' * (colno - 1)
        return f'on line {lineno}\n{line}\n{spaces}*\n'


class Error(Exception):
    def __init__(self, tokens: Iterable[Token], message: str) -> None:
        super().__init__(''.join(token.info for token in tokens) + message)


class Pattern(abc.ABC):
    @abc.abstractmethod
    def match(self, source: Source, i: int) -> Optional[Tuple[Token, int]]:
        pass


class RegexPattern(Pattern):
    def __init__(
            self,
            regex: Union[typing.Pattern[str], str],
            *,
            type: Optional[str] = None,
            type_callback: Callable[[str], str] = lambda value: value,
            value_callback: Callable[[str], object] = lambda x: x) -> None:
        if isinstance(regex, str):
            regex = re.compile(regex)

        if type is not None:
            type_ = str(type)  # for mypy
            type_callback = lambda _: type_

        self.regex = regex
        self.type_callback = type_callback
        self.value_callback = value_callback

    def match(self, source: Source, i: int) -> Optional[Tuple[Token, int]]:
        m = self.regex.match(source.data, i)
        if m is None:
            return None

        raw_value = m.group()
        type_ = self.type_callback(raw_value)
        value = self.value_callback(raw_value)
        return Token(type_, value, source, i), m.end()


def _make_lexer():
    whitespace_pattern = RegexPattern(r'\s+')

    class Lexer:
        def __init__(
                self,
                patterns: List[Pattern],
                *,
                ignore_pattern: Pattern,
                filter: Callable[[Token], Optional[Token]] = lambda token: token
        ) -> None:
            self.patterns = patterns
            self.ignore_pattern = ignore_pattern
            self.filter = filter

        def lex(self, source: Union[Source, str]) -> List[Token]:
            if isinstance(source, str):
                source = Source('<string>', source)

            ignore_pattern = self.ignore_pattern
            i = 0
            s = source.data
            tokens = []

            while True:
                while True:
                    match = ignore_pattern.match(source, i)
                    if match is None:
                        break
                    _, i = match

                if i >= len(s):
                    break

                for pattern in self.patterns:
                    match = pattern.match(source, i)
                    if match is not None:
                        unfiltered_token, i = match
                        token = self.filter(unfiltered_token)
                        if token is not None:
                            tokens.append(token)
                        break
                else:
                    token = Token('ERR', None, source, i)
                    raise Error([token], 'Unrecognized token')

            tokens.append(Token('EOF', None, source, i))
            return tokens

    class MatchingBracesSkipSpacesFilter:
        """A lexer filter for ignoring newlines that appear inside parentheses
        or square brackets.
        """

        def __init__(self) -> None:
            self.stack: List[Token] = []

        def should_skip_newlines(self) -> bool:
            return bool(self.stack and self.stack[-1].type != '{')

        def __call__(self, token: Token) -> Optional[Token]:
            if token.type in ('{', '[', '('):
                self.stack.append(token)

            if token.type in ('}', ']', ')'):
                self.stack.pop()

            if token.type == '\n' and self.should_skip_newlines():
                return None

            return token

    def make_symbols_pattern(symbols: Iterable[str]) -> Pattern:
        return RegexPattern('|'.join(map(re.escape, reversed(sorted(symbols)))))

    def make_keywords_pattern(keywords: Iterable[str]) -> Pattern:
        return RegexPattern('|'.join(r'\b' + kw + r'\b' for kw in keywords))

    name_pattern = RegexPattern(
        '\w+', type='NAME', value_callback=lambda value: value)

    def string_pattern_value_callback(value: str) -> str:
        return str(eval(value))  # type: ignore

    string_pattern_regex = '|'.join([
        r'(?:r)?"""(?:(?:\\.)|(?!""").)*"""',
        r"(?:r)?'''(?:(?:\\.)|(?!''').)*'''",
        r'(?:r)?"(?:(?:\\.)|(?!").)*"',
        r"(?:r)?'(?:(?:\\.)|(?!').)*'",
    ])

    string_pattern = RegexPattern(
        string_pattern_regex,
        type='STRING',
        value_callback=string_pattern_value_callback)

    float_pattern = RegexPattern(
        r'\d+\.\d*|\.\d+', type='FLOAT', value_callback=eval)  # type: ignore
    int_pattern = RegexPattern(
        r'\d+', type='INT', value_callback=eval)  # type: ignore

    def make_simple_lexer(*, keywords: Iterable[str], symbols: Iterable[str]):
        keywords_pattern = make_keywords_pattern(keywords)
        symbols_pattern = make_symbols_pattern(symbols)
        return Lexer(
            [
                string_pattern,
                keywords_pattern,
                float_pattern,
                int_pattern,
                name_pattern,
                symbols_pattern,
            ],
            ignore_pattern=whitespace_pattern)

    return make_simple_lexer(keywords=KEYWORDS, symbols=SYMBOLS)


_lexer = _make_lexer()


def lex(source):
    return _lexer.lex(source)


class FractalStringBuilder(object):
    def __init__(self, depth):
        self.parts = []
        self.depth = depth

    def __str__(self):
        parts = []
        self._dump(parts)
        return ''.join(parts)

    def _dump(self, parts):
        for part in self.parts:
            if isinstance(part, FractalStringBuilder):
                part._dump(parts)
            else:
                parts.append(str(part))

    def __iadd__(self, line):
        if '\n' in line:
            raise TypeError()
        self('  ' * self.depth + line + '\n')
        return self

    def __call__(self, s):
        self.parts.append(s)
        return self

    def spawn(self, depth_diff=0):
        child = FractalStringBuilder(self.depth + depth_diff)
        self.parts.append(child)
        return child


class FakeType(object):
    @property
    def __name__(self):
        return repr(self)


class ListType(FakeType):
    def __init__(self, subtype):
        self.subtype = subtype

    def __getitem__(self, subtype):
        return ListType(subtype)

    def __instancecheck__(self, obj):
        return (
            isinstance(obj, list) and
            all(isinstance(x, self.subtype) for x in obj))

    def __repr__(self):
        return 'List[%s]' % (self.subtype.__name__, )


List = ListType(object)


class OptionalType(object):
    def __init__(self, subtype):
        self.subtype = subtype

    def __getitem__(self, subtype):
        return OptionalType(subtype)

    def __instancecheck__(self, obj):
        return obj is None or isinstance(obj, self.subtype)

    def __repr__(self):
        return 'Optional[%s]' % (self.subtype.__name__, )


Optional = OptionalType(object)


class Scope(object):
    def __init__(self, parent):
        self.parent = parent
        self.table = dict()
        self.pulled = set()  # set of names that were pulled from parent scope
        self.local_definitions = []

    def _set(self, name, node):
        if name in self.table:
            raise Error([self.table[name].token, node.token],
                        f'Name {name} conflict')
        self.table[name] = node

    def add(self, node):
        self.local_definitions.append(node)
        if isinstance(node, GlobalDefinition):
            self._set(node.name, node)
        elif isinstance(node, BaseVariableDefinition):
            self.validate_vardef(node)
            if isinstance(node, VariableDefinition):
                self._check_for_shadow(node)
            self._set(node.name, node)
        else:
            raise Error([node.token], f'FUBAR: Unrecognized node type {node}')

    def validate_vardef(self, vardef):
        if vardef.type not in PRIMITIVE_TYPES and vardef.type != 'var':
            typenode = self.get(vardef.type, [vardef.token])
            if not isinstance(typenode, TypeDefinition):
                raise Error([vardef.token], f'{vardef.type} is not a type')

    def _check_for_shadow(self, node):
        # We need to take care not to shadow VariableDefinitions.
        # If VariableDefinitions are ever shadowed, they will cause
        # incorrect behavior when the function tries to release
        # all local variables before a return.
        scope = self.parent
        name = node.name
        while scope:
            if name in scope.table and isinstance(scope.table[name], VariableDefinition):
                raise Error([node.token, scope.table[name].token],
                            f'Shadowed local variable')
            scope = scope.parent

    def _missing_name_err(self, name, tokens):
        return Error(tokens, f'Name {name} not defined in this scope')

    def pull(self, name, tokens):
        """Pull a name from parent scope.
        The purpose of doing this is so that if an outer variable is
        used, then a user tries to declare a variable of the same name,
        we want to error out and tell the user that that's funky.
        """
        if name not in self.table:
            if self.parent is None:
                raise self._missing_name_err(name, tokens)
            self.table[name] = self.parent.pull(name, tokens)
            self.pulled.add(name)
        return self.table[name]

    def get(self, name, tokens):
        if name in self.table:
            return self.table[name]
        elif self.parent is not None:
            return self.parent.get(name, tokens)
        raise self._missing_name_err(name, tokens)


class Node(object):
    def __init__(self, token, *args):
        self.token = token
        for (fname, ftype), arg in zip(type(self).fields, args):
            # sys.stderr.write('ftype = %r\n' % (ftype, ))
            if not isinstance(arg, ftype):
                raise TypeError('Expected type of %r to be %r, but got %r' % (
                    fname, ftype, arg))
            try:
                setattr(self, fname, arg)
            except AttributeError:
                sys.stderr.write(f'fname = {fname}\n')
                raise
        if len(type(self).fields) != len(args):
            raise TypeError('%s expects %s arguments, but got %s' % (
                type(self).__name__, len(type(self).fields), len(args)))

    def __repr__(self):
        return '%s(%s)' % (
            type(self).__name__,
            ', '.join(repr(getattr(self, n)) for n, _ in type(self).fields),
        )


def _crelease(ctx, type_, cname):
    if type_ in PRIMITIVE_TYPES:
        return ''
    elif type_ == 'var':
        return f'KLC_release_var({cname});'
    else:
        return f'KLC_release((KLC_header*) {cname});'


def _cretain(ctx, type_, cname):
    if type_ in PRIMITIVE_TYPES:
        return ''
    elif type_ == 'var':
        return f'KLC_retain_var({cname});'
    else:
        return f'KLC_retain((KLC_header*) {cname});'


class BaseVariableDefinition(Node):
    fields = (
        ('type', str),
        ('name', str),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.type == 'void':
            raise Error([self.token], f'Variable of type void is not allowed')

    def cproto(self, ctx):
        return f'{ctx.cdecltype(self.type)} {ctx.cname(self.name)}'

    def cname(self, ctx):
        return ctx.cname(self.name)

    def crelease(self, ctx):
        return _crelease(ctx, self.type, self.cname(ctx))

    def cretain(self, ctx):
        return _cretain(ctx, self.type, self.cname(ctx))


class Parameter(BaseVariableDefinition):
    pass


class Field(BaseVariableDefinition):
    pass


class GlobalDefinition(Node):
    pass


class Statement(Node):
    def translate(self, ctx):
        """Translates self with the given translation context.
        Returns True if the current statement is terminal (e.g. return).
        No statements directly after a translate that returns True should
        be emitted, since those following statements will be unreachable.
        """
        raise NotImplementedError()


class Expression(Node):
    def translate(self, ctx):
        """Translates self with the given translation context.
        Returns (type, tempvar) pair, where type is the type of
        evaluating this expression, and tempvar is the name of the
        temporary C variable where the result of this expression
        is stored.
        If type is 'void', tempvar should be None.
        """
        raise NotImplementedError()


class TranslationContext(object):
    def __init__(self, scope):
        self.scope = scope

    def cdecltype(self, name):
        if name in PRIMITIVE_TYPES:
            if name == 'function':
                return 'KLC_Function'
            else:
                return name
        elif name == 'var':
            return 'KLC_var'
        else:
            return f'{self.cname(name)}*'

    def cname(self, name):
        return f'KLCN{name}'

    def czero(self, name):
        if name in PRIMITIVE_TYPES:
            return '0'
        elif name == 'var':
            return 'KLC_zero'
        else:
            return 'NULL'

    def varify(self, type_, cname):
        if type_ == 'var':
            return cname
        elif type_ in PRIMITIVE_TYPES:
            return f'KLC_{type_}_to_var({cname})'
        else:
            return f'KLC_object_to_var((KLC_header*) {cname})'


class Name(Expression):
    fields = (
        ('name', str),
    )

    def translate(self, ctx):
        defn = ctx.scope.get(self.name, [self.token])
        if not isinstance(defn, BaseVariableDefinition):
            raise Error([self.token, defn.token],
                        f'{name} is not a variable')
        etype = defn.type
        tempvar = ctx.mktemp(etype)
        ctx.src += f'{tempvar} = {ctx.cname(self.name)};'
        ctx.src += _cretain(ctx, etype, tempvar)
        return (etype, tempvar)


class StringLiteral(Expression):
    fields = (
        ('value', str),
    )

    def translate(self, ctx):
        tempvar = ctx.mktemp('String')
        # TODO: properly escape the string literal
        s = (self.value
            .replace('\\', '\\\\')
            .replace('\t', '\\t')
            .replace('\n', '\\n'))
        ctx.src += f'{tempvar} = KLC_mkstr("{s}");'
        return ('String', tempvar)


class FunctionCall(Expression):
    fields = (
        ('function', str),
        ('args', List[Expression]),
    )

    def translate(self, ctx):
        defn = ctx.scope.get(self.function, [self.token])
        if not isinstance(defn, FunctionDefinition):
            raise Error([self.token, defn.token],
                        f'{self.function} is not a function')
        argtempvars = []
        for param, arg in zip(defn.params, self.args):
            argtype, argtempvar = arg.translate(ctx)
            argtempvars.append(argtempvar)
            if argtype != param.type:
                raise Error([param.token, arg.token],
                            f'Expected {param.type} but got {argtype}')
        if len(defn.params) != len(self.args):
            raise Error([self.token, defn.token],
                        f'{len(defn.params)} args expected '
                        f'but got {len(self.args)}')
        argsstr = ', '.join(argtempvars)
        if defn.return_type is 'void':
            ctx.src += f'{ctx.cname(defn.name)}({argsstr});'
            return ('void', None)
        else:
            tempvar = ctx.mktemp(defn.return_type)
            ctx.src += f'{tempvar} = {ctx.cname(defn.name)}({argsstr});'
            return (defn.return_type, tempvar)



class VariableDefinition(Statement, BaseVariableDefinition):
    fields = BaseVariableDefinition.fields + (
        ('expression', Optional[Expression]),
    )

    def translate(self, ctx):
        ctx.scope.add(self)
        if self.expression:
            ectx = ctx.ectx()
            etype, tempvar = self.expression.translate(ectx)
            value = tempvar
            if self.type == 'var' and etype != 'void':
                value = ctx.varify(etype, tempvar)
            elif self.type != etype:
                raise Error([self.token],
                            f'Expected {self.type} but got {etype}')
            ectx.src += f'{self.cname(ectx)} = {value};'
            ectx.release_tempvars(tempvar)


class ExpressionStatement(Statement):
    fields = (
        ('expression', Optional[Expression]),
    )

    def translate(self, ctx):
        ectx = ctx.ectx()
        self.expression.translate(ectx)
        ectx.release_tempvars()


class Return(Statement):
    fields = (
        ('expression', Optional[Expression]),
    )

    def translate(self, ctx):
        ectx = ctx.ectx()
        if self.expression:
            rtype, tempvar = self.expression.translate(ectx)
        else:
            rtype = 'void'
        fctx = ctx.fctx
        expected_rtype = fctx.fdef.return_type
        if expected_rtype != rtype:
            raise Error([fctx.fdef.token, self.token],
                        f'Function was declared to return {expected_rtype} '
                        f'but tried to return {rtype} instead')
        if rtype == 'void':
            _release_for_return(ctx, ectx.src)
            ectx.src += 'return;'
        else:
            ectx.release_tempvars(tempvar)
            _release_for_return(ctx, ectx.src)
            ectx.src += f'return {tempvar};'

        return True


def _release_for_return(ctx, src):
    # Before returning, we should release all local variables
    # We need to take care not to release function parameters
    # or global variables
    scope = ctx.scope
    while scope:
        for vdef in reversed(scope.local_definitions):
            if isinstance(vdef, VariableDefinition):
                src += vdef.crelease(ctx)
        scope = scope.parent


class Block(Statement):
    fields = (
        ('statements', List[Statement]),
    )

    def translate(self, pctx):
        pctx.src += '{'
        prologue = pctx.src.spawn(1)
        ctx = pctx.bctx(1)
        epilogue = pctx.src.spawn(1)
        pctx.src += '}'
        early_return = False
        for i, statement in enumerate(self.statements):
            if statement.translate(ctx):
                early_return = True
                if i + 1 < len(self.statements):
                    raise Error([self.statements[i + 1].token],
                                'Unreachable statement')
                break

        # Declare the local variables for C
        # To be C89 compatible, we need all variable definitions
        # to appear at the beginning of the block.
        for vdef in ctx.scope.local_definitions:
            assert isinstance(vdef, VariableDefinition), vdef
            prologue += f'{vdef.cproto(ctx)} = {ctx.czero(vdef.type)};'

        # If there's an early return, there's no need to have an
        # epilogue and generate unreachable code.
        if not early_return:
            # If we don't have an early return, we should
            # make sure to release all local variables defined in
            # this block before exiting
            # We should also release in LIFO order
            for vdef in reversed(ctx.scope.local_definitions):
                if vdef.type not in PRIMITIVE_TYPES:
                    epilogue += vdef.crelease(ctx)


class GlobalTranslationContext(TranslationContext):
    def __init__(self, program):
        super().__init__(Scope(None))
        for d in program.definitions:
            self.scope.add(d)
        self.out = FractalStringBuilder(0)
        self.out(PRELUDE)
        self.fwd = self.out.spawn()
        self.hdr = self.out.spawn()
        self.src = self.out.spawn()

    def fctx(self, fdef):
        "Create child function translation context"
        return FunctionTranslationContext(self, fdef)


class BodyTranslationContext(TranslationContext):

    def bctx(self, depth):
        return BlockTranslationContext(self, depth)


class FunctionTranslationContext(BodyTranslationContext):
    def __init__(self, gctx, fdef):
        super().__init__(Scope(gctx.scope))
        for param in fdef.params:
            self.scope.add(param)
        self.parent = gctx
        self.fdef = fdef
        self.hdr = gctx.hdr.spawn()
        self.src = gctx.src.spawn()
        self.fctx = self


class BlockTranslationContext(BodyTranslationContext):
    def __init__(self, parent: BodyTranslationContext, depth):
        super().__init__(Scope(parent.scope))
        self.parent = parent
        self.fctx = parent.fctx
        self.src = parent.src.spawn(depth)

    def ectx(self):
        return ExpressionTranslationContext(self)


class ExpressionTranslationContext(TranslationContext):
    def __init__(self, parent: BlockTranslationContext):
        super().__init__(parent.scope)
        self.parent = parent
        self.tempdecls = []  # (type, cname) pairs of temporary vars
        parent.src += '{'
        self.tmp = parent.src.spawn(1)
        self.src = parent.src.spawn(1)
        parent.src += '}'
        self.next_tempvar_index = 0

    def mktemp(self, type_):
        i = self.next_tempvar_index
        self.next_tempvar_index += 1
        tempvar = f'tempvar{i}'
        self.tempdecls.append((type_, tempvar))
        self.tmp += f'{self.cdecltype(type_)} {tempvar} = {self.czero(type_)};'
        return tempvar

    def release_tempvars(self, keepvar=None):
        """Release all temporary variables used during expression
        evaluation, except the specified keepvar.
        Variables are released in LIFO order
        """
        for type_, cname in reversed(self.tempdecls):
            if cname != keepvar:
                self.src += _crelease(self, type_, cname)


class Program(Node):
    fields = (
        ('definitions', List[GlobalDefinition]),
    )

    def translate(self):
        ctx = GlobalTranslationContext(self)
        for d in self.definitions:
            d.translate(ctx)
        return str(ctx.out)


class FunctionDefinition(GlobalDefinition):
    fields = (
        ('return_type', str),
        ('name', str),
        ('params', List[Parameter]),
        ('body', Optional[Block]),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.name == 'main':
            if self.return_type != 'void' or len(self.params):
                raise Error([self.token],
                            'main function must have signature '
                            "'void main()'")

    @property
    def extern(self):
        return self.body is None

    def cproto(self, ctx):
        crt = ctx.cdecltype(self.return_type)
        cname = ctx.cname(self.name)
        cparams = ', '.join(p.cproto(ctx) for p in self.params)
        return f'{crt} {cname}({cparams})'

    def translate(self, gctx: GlobalTranslationContext):
        ctx = gctx.fctx(self)
        ctx.hdr += self.cproto(ctx) + ';'
        if self.body:
            ctx.src += self.cproto(ctx)
            self.body.translate(ctx)


class TypeDefinition(GlobalDefinition):
    pass


class ClassDefinition(TypeDefinition):
    fields = (
        ('name', str),
        ('fields', Optional[List[Field]]),
    )

    @property
    def extern(self):
        return self.fields is None

    def translate(self, ctx: GlobalTranslationContext):
        name = self.name
        cname = ctx.cname(name)
        cdecltype = ctx.cdecltype(name)

        del_name = f'KLC_delete{name}'
        malloc_name = f'KLC_malloc{name}'

        delete_proto = f'void {del_name}(KLC_header* robj, KLC_header** dq)'
        malloc_proto = f'{cdecltype} {malloc_name}()'

        ctx.hdr += delete_proto + ';'
        ctx.hdr += malloc_proto + ';'

        if self.extern:
            return

        ctx.fwd += f'typedef struct {cname} {cname};'

        ctx.hdr += f'struct {cname} ' '{'
        ctx.hdr += '  KLC_header header;'
        for field in self.fields:
            ctx.hdr += f'  {field.cproto(ctx)};'
        ctx.hdr += '};'

        ctx.src += f'KLC_typeinfo KLC_type{name} = ' '{'
        ctx.src += f'  "{name}",'
        ctx.src += f'  &{del_name}'
        ctx.src += '};'

        ctx.src += delete_proto + '{'
        objfields = [f for f in self.fields if f.type not in PRIMITIVE_TYPES]
        if objfields:
            ctx.src += f'  {cdecltype} obj = ({cdecltype}) robj;'
            for field in objfields:
                cfname = ctx.cname(field.name)
                if field.type == 'var':
                    ctx.src += f'  KLC_partial_release_var(obj->{cfname}, dq);'
                else:
                    ctx.src += f'  KLC_partial_release((KLC_header*) obj->{cfname}, dq);'
        ctx.src += '}'

        ctx.src += malloc_proto + '{'
        ctx.src += f'  {cdecltype} obj = ({cdecltype}) malloc(sizeof({cname}));'
        for field in self.fields:
            cfname = ctx.cname(field.name)
            ctx.src += f'  obj->{cfname} = {ctx.czero(field.type)};'
        ctx.src += '  return obj;'
        ctx.src += '}'



def translate(*sources):
    i = tokens = None

    global_token_map = dict()

    todo = []  # list of callbacks to invoke after scope is populated

    out = FractalStringBuilder(0)
    out(PRELUDE)
    fwd = out.spawn()  # forward decls
    hdr = out.spawn()  # header
    dlt = out.spawn()  # deleter functions
    tpi = out.spawn()  # typeinfo definitions
    cst = out.spawn()  # constructor functions
    src = out.spawn()  # function definitions

    def _cdecltype(name):
        if name in PRIMITIVE_TYPES:
            return name
        else:
            return f'KLCN{name}*'

    def set_token_for_global_name(name, token):
        if name in global_token_map:
            throw(f'Conflicting definitions for {name}',
                  [global_token_map[name], token])
        global_token_map[name] = token

    def throw(message, tokens=None):
        raise Error([peek()] if tokens is None else tokens, message)

    def peek(lookahead=0):
        return tokens[min(i + lookahead, len(tokens) - 1)]

    def gettok():
        nonlocal i
        token = tokens[i]
        i += 1
        return token

    def at(token_type, lookahead=0):
        return peek(lookahead).type == token_type

    def consume(token_type):
        if at(token_type):
            return gettok()

    def expect(token_type):
        if not at(token_type):
            throw(f'Expected {token_type} but got {peek()}')
        return gettok()

    hdr('\n/* header */\n')
    dlt('\n/* deleters */\n')
    tpi('\n/* typeinfo definitions */\n')
    cst('\n/* constructors */\n')
    src('\n/* source */\n')

    def translate_class():
        token = expect('class')
        name = expect('NAME').value
        set_token_for_global_name(name, token)

        fwd(f'typedef struct KLCN{name} KLCN{name};\n')

        if consume(';'):
            return

        dlt(f'void KLC_delete{name}(KLC_header* robj, KLC_header** dq) ')
        dlt('{\n')
        dlt(f'  KLCN{name}* obj = (KLCN{name}*) robj;\n')

        tpi(f'KLC_typeinfo KLC_type{name} = ' '{\n')
        tpi(f'  "{name}",\n')
        tpi(f'  KLC_delete{name}\n')
        tpi('};\n')

        cst(f'KLCN{name}* KLC_malloc{name}() ')
        cst('{\n')
        cst(f'  KLCN{name}* obj = (KLCN{name}*) malloc(sizeof(KLCN{name}));\n')
        cst(f'  obj->header.type = &KLC_type{name};\n')
        cst(f'  obj->header.refcnt = 0;\n')
        cst(f'  obj->header.next = NULL;\n')

        hdr(f'struct KLCN{name} ')
        hdr('{\n')
        hdr('  KLC_header header;\n')

        field_token_map = dict()
        expect('{')
        while not consume('}'):
            if at('NAME') and at('NAME', 1) and at(';', 2):
                field_token = peek()
                field_type = expect('NAME').value
                field_name = expect('NAME').value
                expect(';')

                hdr(f'  {_cdecltype(field_type)} KLCN{field_name};\n')

                if field_type in PRIMITIVE_TYPES:
                    cst(f'  obj->KLCN{field_name} = 0;\n')
                else:
                    dlt(f'  KLC_partial_release((KLC_header*) obj->KLCN{field_name}, dq);\n')
                    cst(f'  obj->KLCN{field_name} = NULL;\n')

                if field_name in field_token_map:
                    throw(f'Duplicate field definition for {name}.{field_name}',
                          tokens=[field_token, field_token_map[field_name]])
            else:
                throw(f'Expected field or method definition but got {peek()}')

        cst('  return obj;\n')

        hdr('};\n')
        dlt('}\n')
        cst('}\n')

    def translate_function():
        token = peek()
        return_type = expect('NAME').value
        name = expect('NAME').value
        set_token_for_global_name(name, token)
        params = []
        expect('(')
        while at('NAME'):
            param_type = expect('NAME').value
            param_name = expect('NAME').value
            params.append((param_type, param_name))
            if not consume(','):
                break
        expect(')')
        argsstr = ', '.join(f'{_cdecltype(t)} KLCN{n}' for t, n in params)
        proto = f'{_cdecltype(return_type)} KLCN{name}({argsstr})'

        hdr(f'{proto};\n')

        if not consume(';'):
            src(f'{proto} ' "{\n")
            translate_block(1)
            src('}\n')

    def translate_statement(depth):
        if at('{'):
            translate_block(depth)
        else:
            throw('Expected statement')

    class ExpressionContext:
        def __init__(self, depth):
            self.tempvars = []
            self.depth = depth

    @contextlib.contextmanager
    def expression_context(depth):
        ec = ExpressionContext(depth)
        yield ec

        for tempvar in reversed(ec.tempvars):
            indent(depth)
            src(f'KLC_release((KLC_header*) {tempvar})')

    def translate_expression(ec, depth):
        pass

    def indent(depth):
        src('  ' * depth)

    def translate_block(depth):
        indent(depth)
        src('{\n')

        expect('{')
        while not consume('}'):
            translate_statement(depth + 1)

        indent(depth)
        src('}\n')

    def translate_source(source):
        nonlocal tokens, i
        tokens = lex(source)
        i = 0
        while not at('EOF'):
            if at('class'):
                translate_class()
            elif at('NAME') and at('NAME', 1) and at('(', 2):
                translate_function()
            else:
                throw(f'Expected global definition but got {peek()}')

    for source in sources:
        translate_source(source)

    for callback in todo:
        callback()

    return str(out)


tok = lex(Source('<dummy>', 'dummy'))[0]

node = Program(tok, [
    ClassDefinition(tok, 'String', None),
    ClassDefinition(tok, 'Foo', [
        Field(tok, 'var', 'v'),
        Field(tok, 'int', 'i'),
        Field(tok, 'String', 's'),
    ]),
    FunctionDefinition(tok, 'void', 'puts', [Parameter(tok, 'String', 'x')], None),
    FunctionDefinition(tok, 'String', 'id', [Parameter(tok, 'String', 'x')], Block(tok, [
        Return(tok, StringLiteral(tok, 'id-result')),
    ])),
    FunctionDefinition(tok, 'void', 'main', [], Block(tok, [
        ExpressionStatement(tok, FunctionCall(
            tok, 'puts', [StringLiteral(tok, 'Hello world!')]
        )),
        VariableDefinition(tok, "String", "s", StringLiteral(tok, "Hello world2")),
        VariableDefinition(tok, "var", "v", StringLiteral(tok, "Hello world2")),
        ExpressionStatement(tok, FunctionCall(tok, 'puts', [Name(tok, 's')])),
        ExpressionStatement(tok, FunctionCall(tok, 'puts', [
            FunctionCall(tok, 'id', [StringLiteral(tok, 'id-arg')]),
        ])),
    ])),
])

print(node.translate())


# print(lex(Source('<string>', 'abc + def')))
# print(translate(Source('<string>', """
# class String;
# class List;
#
# class Foo {
#   size_t i;
#   int x;
# }
#
# class Bar {
#   Foo foo;
# }
#
# void puts(String s);
# String sprintf(String fmt, List args);
#
# void main() {}
#
# """)))
