/* Autogenerated by the KL Compiler */
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#define KLC_TAG_INT 0
#define KLC_TAG_LONG 1
#define KLC_TAG_SIZE_T 2
#define KLC_TAG_DOUBLE 3
#define KLC_TAG_FUNCTION 4
#define KLC_TAG_OBJECT 5

typedef struct KLC_header KLC_header;
typedef struct KLC_typeinfo KLC_typeinfo;
typedef struct KLC_var KLC_var;
typedef KLC_var (*KLC_Function)(int, KLC_var*);

struct KLC_header {
  KLC_typeinfo* type;
  size_t refcnt;
  KLC_header* next;
};

struct KLC_typeinfo {
  const char* name;
  void (*deleter)(KLC_header*, KLC_header**);
};

struct KLC_var {
  int tag;
  union {
    int i;
    long l;
    size_t s;
    double d;
    KLC_Function f;
    KLC_header* obj;
  } u;
};

void KLC_retain(KLC_header *obj) {
  if (obj) {
    obj->refcnt++;
  }
}

void KLC_retain_var(KLC_var v) {
  if (v.tag == KLC_TAG_OBJECT) {
    KLC_retain(v.u.obj);
  }
}

void KLC_partial_release(KLC_header* obj, KLC_header** delete_queue) {
  if (obj) {
    if (obj->refcnt) {
      obj->refcnt--;
    } else {
      obj->next = *delete_queue;
      *delete_queue = obj;
    }
  }
}

void KLC_partial_release_var(KLC_var v, KLC_header** delete_queue) {
  if (v.tag == KLC_TAG_OBJECT) {
    KLC_partial_release(v.u.obj, delete_queue);
  }
}

void KLC_release(KLC_header *obj) {
  KLC_header* delete_queue = NULL;
  KLC_partial_release(obj, &delete_queue);
  while (delete_queue) {
    obj = delete_queue;
    delete_queue = delete_queue->next;
    obj->type->deleter(obj, &delete_queue);
    free(obj);
  }
}

void KLC_release_var(KLC_var v) {
  if (v.tag == KLC_TAG_OBJECT) {
    KLC_release(v.u.obj);
  }
}

KLC_var KLC_int_to_var(int i) {
  KLC_var ret;
  ret.tag = KLC_TAG_INT;
  ret.u.i = i;
  return ret;
}

KLC_var KLC_object_to_var(KLC_header* obj) {
  KLC_var ret;
  ret.tag = KLC_TAG_OBJECT;
  ret.u.obj = obj;
  return ret;
}

typedef struct KLCNString KLCNString;
struct KLCNString {
  KLC_header header;
  size_t size;
  char *buffer;
};

void KLC_deleteString(KLC_header* robj, KLC_header** dq) {
  KLCNString *obj = (KLCNString*) robj;
  free(obj->buffer);
}

KLC_typeinfo KLC_typeString = {
  "String",
  KLC_deleteString
};

KLCNString* KLC_mkstr(const char *str) {
  KLCNString* obj = (KLCNString*) malloc(sizeof(KLCNString));
  size_t len = strlen(str);
  char* buffer = (char*) malloc(sizeof(char) * (len + 1));
  strcpy(buffer, str);
  obj->header.type = &KLC_typeString;
  obj->header.refcnt = 0;
  obj->header.next = NULL;
  obj->size = len;
  obj->buffer = buffer;
  return obj;
}

void KLCNputs(KLCNString *s) {
  printf("%s\n", s->buffer);
}

void KLCNmain();

KLC_var KLC_zero;

int main() {
  KLCNmain();
  return 0;
}

typedef struct KLCNFoo KLCNFoo;
struct KLCNFoo {
  KLC_header header;
  KLC_var KLCNv;
  int KLCNi;
  KLCNString* KLCNs;
};
void KLC_deleteFoo(KLC_header* robj, KLC_header** dq);
KLCNFoo* KLC_mallocFoo();
void KLCNputs(KLCNString* KLCNx);
KLCNString* KLCNid(KLCNString* KLCNx);
void KLCNmain();
KLC_typeinfo KLC_typeFoo = {
  "Foo",
  &KLC_deleteFoo
};
void KLC_deleteFoo(KLC_header* robj, KLC_header** dq){
  KLCNFoo* obj = (KLCNFoo*) robj;
  KLC_partial_release_var(obj->KLCNv, dq);
  KLC_partial_release((KLC_header*) obj->KLCNs, dq);
}
KLCNFoo* KLC_mallocFoo(){
  KLCNFoo* obj = (KLCNFoo*) malloc(sizeof(KLCNFoo));
  obj->KLCNv = KLC_zero;
  obj->KLCNi = 0;
  obj->KLCNs = NULL;
  return obj;
}
KLCNString* KLCNid(KLCNString* KLCNx)
{
  {
    KLCNString* tempvar0 = NULL;
    tempvar0 = KLC_mkstr("id-result");
    return tempvar0;
  }
}
void KLCNmain()
{
  KLCNString* KLCNs = NULL;
  KLC_var KLCNv = KLC_zero;
  {
    KLCNString* tempvar0 = NULL;
    tempvar0 = KLC_mkstr("Hello world!");
    KLCNputs(tempvar0);
    KLC_release((KLC_header*) tempvar0);
  }
  {
    KLCNString* tempvar0 = NULL;
    tempvar0 = KLC_mkstr("Hello world2");
    KLCNs = tempvar0;
  }
  {
    KLCNString* tempvar0 = NULL;
    tempvar0 = KLC_mkstr("Hello world2");
    KLCNv = KLC_object_to_var((KLC_header*) tempvar0);
  }
  {
    KLCNString* tempvar0 = NULL;
    tempvar0 = KLCNs;
    KLC_retain((KLC_header*) tempvar0);
    KLCNputs(tempvar0);
    KLC_release((KLC_header*) tempvar0);
  }
  {
    KLCNString* tempvar0 = NULL;
    KLCNString* tempvar1 = NULL;
    tempvar0 = KLC_mkstr("id-arg");
    tempvar1 = KLCNid(tempvar0);
    KLCNputs(tempvar1);
    KLC_release((KLC_header*) tempvar1);
    KLC_release((KLC_header*) tempvar0);
  }
  KLC_release_var(KLCNv);
  KLC_release((KLC_header*) KLCNs);
}

